# Hypothesis testing problems

## Exercise 1

You are a nutritionist researching two different types of diets to see if there is a significant difference in weight loss after one month. You choose two random groups of people, one group follows the first diet and the other follows the second. At the end of the month, you record the weight loss (in kg) for each person:

| Diet 1 | Diet 2 |
|:-------|:-------|
| 2.0 | 3.0 |
| 2.5 | 3.2 |
| 3.0 | 3.1 |
| 2.8 | 2.9 |
| 2.3 | 2.8 |
| 2.7 | 3.0 |
| 2.5 | 3.2 |

With these data, it seeks to answer the following question: is there a significant difference in average weight loss between people who followed the first diet and those who followed the second diet?

To draw conclusions, follow the points below:

- State the hypothesis: null and alternative hypothesis.
- Perform the test to test the hypothesis. You can use a Student's t-test.
- Analyze the conclusions.

In [8]:
# TODO
import numpy as np
import scipy.stats as stats

Diet_1 = [2.0, 2.5, 3.0, 2.8, 2.3, 2.7, 2.5]
Diet_2 = [3.0, 3.2, 3.1, 2.9, 2.8, 3.0, 3.2]

#Null hypothesis: there is no difference between the diets
#Alternate hypothesis: there is a significant difference between the diets

#average weight losses
Average_1 = np.mean(Diet_1).round(2)
Average_2 = np.mean(Diet_2).round(2)

print(f"The average weight loss of the group which followed diet 1 is of {Average_1}")
print(f"The average weight loss of the group which followed diet 2 is of {Average_2}")
#t-test

t_value, p_value = stats.ttest_ind(Diet_1, Diet_2)

print(f"The student t-test gave a p-value of {p_value}")



The average weight loss of the group which followed diet 1 is of 2.54
The average weight loss of the group which followed diet 2 is of 3.03
The student t-test gave a p-value of 0.004083270191713912


Given that the p-value lies well under the 5% threshhold or 0.05, the deviation of the results can be deemed as significant. This confirms the results obtained from the average weight-loss measurements that Diet 2 is the more effective option.

## ANOVA

**ANOVA** (*Analysis of Variance*) is a statistical technique used to compare the measures of two or more groups. The idea behind ANOVA is to decompose the total variability in the data into two components: between-group variability and within-group variability:

- **Between-group variability**: This variability refers to the differences between the group means. If this variability is considerably larger than the within-group variability, it could be an indication that at least one of the group means is different.
- **Within-group variability**: This variability refers to the dispersion of the data within each group. If all groups have similar variability, then any noticeable difference in group means could be considered significant.

Hypotheses in ANOVA typically are:

- **Null hypothesis** ($H₀$): The means of all groups are equal.
- **Alternative hypothesis** ($H₁$): At least one of the group means is different.

If the ANOVA test result is significant (e.g., a p-value less than a threshold such as 0.05), this suggests that at least one group mean is different.

### Exercise 2

A farmer decides to test three different types of fertilizers to determine if one is superior in terms of corn production. The farmer plants corn on 15 identical plots and uses all three fertilizers (5 plots for each type). At the end of the season, he measures the corn yield (in kg) of each plot, with the following result:

| Fertilizer 1 | Fertilizer 2 | Fertilizer 3 |
|:-------------|:-------------|:-------------|
| 20 | 22 | 24 |
| 21 | 21 | 23 |
| 20 | 23 | 22 |
| 19 | 22 | 23 |
| 20 | 21 | 24 |

With this data, he seeks to answer the following question: is there a significant difference in average corn yield between the three types of fertilizers?

To help you, follow the points below:

- State the hypothesis: null and alternative hypothesis.
- Perform the ANOVA test.
- Analyze the conclusions.
- If one fertilizer is better than another, how can we know it?

In [2]:
# TODO
import numpy as np
import scipy.stats as stats

Fertilizer1 = [20, 21, 20, 19, 20]
Fertilizer2 = [22, 21, 23, 22, 21]
Fertilizer3 = [24, 23, 22, 23, 24]

#Null hypothesis: all fertilizers are the same
#Alternative hypothesis: at least one of the fertilizers differs, either for better or worse

average, p_value = stats.f_oneway(Fertilizer1, Fertilizer2, Fertilizer3, axis=0)


print(f"The ANOVA test gave a p-value of {p_value.round(5)}, which means that there is enough difference in the results to disprove the null hypothesis.")

#Choosing the better fertilizer
#Use t-test between indivudial fertilizers to rule out those whose result is too similar:

Combined_experiments = np.array(Fertilizer1 + Fertilizer2 + Fertilizer3)
Exp_matrix = Combined_experiments.reshape(-1,5)
print(Exp_matrix)

for i in range(len(Exp_matrix)):
    if i < (len(Exp_matrix)-1):
        t_value, p_value = stats.ttest_ind(Exp_matrix[i], Exp_matrix[i+1])
        if p_value < 0.05:
            print(f"Fertilizers {i+1} and {i+2} are signifficantly different.")
            
        else:
            print(f"It cannot be stated that fertilizers {i+1} and {i+2} act significantly different.")
        
    else:
        t_value, p_value = stats.ttest_ind(Exp_matrix[i], Exp_matrix[0])
        if p_value < 0.05:
            print(f"Fertilizers {i} and {i-2} are signifficantly different.")
        else:
            print(f"It cannot be stated that fertilizers {i} and {i-2} act significantly different.")

#If they're statistically different, get the mean and compare the results
averages = []
for i in range(len(Exp_matrix)):
    averages.append(np.mean(Exp_matrix[i]))
idmax = np.argmax(averages)

print(f"The fertilizer which provides the best results was fertilizer {idmax+1}.")   



The ANOVA test gave a p-value of 0.00014, which means that there is enough difference in the results to disprove the null hypothesis.
[[20 21 20 19 20]
 [22 21 23 22 21]
 [24 23 22 23 24]]
Fertilizers 1 and 2 are signifficantly different.
Fertilizers 2 and 3 are signifficantly different.
Fertilizers 2 and 0 are signifficantly different.
The fertilizer which provides the best results was fertilizer 3
